# -*- coding: utf-8 -*-
"""522H0006_DangThanhNhan_Lab04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dz5ew5Bj3ccU_Btkf54gc_LMelI2DXrJ

**Đặng Thành Nhân - MSSV:522H0006 - Lab04**
"""

#Example
import random
x = [random.randint(1,6) for i in range(8000)]
X = set(x)
print(x)
print(X)

#Probability distribution
P = [x.count(i)/len(x) for i in X]
print(P)

#CDF: Cumulative distribution function
FX = sum(P[:3])
print(FX)

#Expectations
EX = 0
for x in X:
  EX = EX + (x* P[x-1])
print(EX)

#Variance
VarX = 0
for x in X:
  VarX = VarX + (x-EX)*(x-EX)*P[x-1]
print(VarX)

#Standard Deviation
import math
SD = math.sqrt(VarX)
print(SD)

#Exercise01
import numpy as np
import math
x = np.random.choice([0, 1, 2, 3, 4, 5], 3650, p=[0.1, 0.2, 0.3, 0.2, 0.15, 0.05])
x = x.tolist()
#a
a = [random.randint(0,5) for i in range(3650)]
X = set(a)
print('The values of the random variable X are: ',X, end ='\n')

#b
P = [x.count(i)/len(x) for i in X]
print('The probability distribution function of the random variable X are: ',P, end ='\n')

#c
EX = 0
for x in X:
  EX = EX + (x* P[x-1])
print('The expectation is:', EX, end ='\n')

VarX = 0
for x in X:
  VarX = VarX + (x-EX)*(x-EX)*P[x-1]
print('The variance is:', VarX, end ='\n')

SD = math.sqrt(VarX)
print('The standard deviation is:', SD, end ='\n')

#d
P_more3 = sum(P[3:])
print('The probability of having 3 or more emergency cases is:', P_more3, end ='\n')

#Exercise02
#a
x = [random.randint(0,2) for i in range(10000)]
print('Results', x)

#b
X = set(a)
print('The values of random variable X are:', X, end ='\n')

#c
P = [x.count(i)/len(x) for i in X]
print('The probability distribution function of the random variable X are:',P, end ='\n')

#d
EX = 0
for x in X:
  EX = EX + (x* P[x-1])
print('The expectation is:', EX, end ='\n')

VarX = 0
for x in X:
  VarX = VarX + (x-EX)*(x-EX)*P[x-1]
print('The variance is:', VarX, end ='\n')

SD = math.sqrt(VarX)
print('The standard deviation is:', SD, end ='\n')

#e
P_more1Head = sum(P[1:])
print('The probability to have at least one head is:', P_more1Head)